Repository prgrms-be-devcourse/BE-02-MarBox, pull requests merged in 2022-07, with the labels that each got.

#112 [#107] 사용자는 한 영화관에서 특정 날짜에 상영하는 영화 정보를 확인한다
  src/docs/asciidoc/schedule.adoc
  src/main/java/prgrms/marco/be02marbox/domain/exception/custom/Message.java
  src/main/java/prgrms/marco/be02marbox/domain/exception/handler/TheaterExceptionHandler.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleController.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleService.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleControllerTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceTest.java
Labels: theater

#118 [#114] application-test.yml 데이터소스 엔드포인트 수정하기
  src/main/resources/application-test.yml
Labels: Team-Marco, config, hotfix

#120 [#104] TicketService, TheaterService 주석 추가
  src/main/java/prgrms/marco/be02marbox/domain/reservation/service/TicketService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterService.java
Labels: Team-Marco, reservation, theater

#116 [#105] 예매 가능 좌석 정보 조회, 스케줄 id에 예약된 좌석 정보 조회 리펙토링
  src/main/java/prgrms/marco/be02marbox/domain/reservation/ReservedSeat.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/service/ReservedSeatService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepository.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/RepositoryTestUtil.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepositoryTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryTest.java
Labels: Team-Marco, seat, reserved_seat

#123 [#119] 개발 완료한 API 권한 최신화하기
  src/main/java/prgrms/marco/be02marbox/config/WebSecurityConfigure.java
Labels: Team-Marco, config

#127 [#110] 로그인 기능 추가 개발
  src/docs/asciidoc/user.adoc
  src/main/java/prgrms/marco/be02marbox/config/WebSecurityConfigure.java
  src/main/java/prgrms/marco/be02marbox/domain/exception/custom/Message.java
  src/main/java/prgrms/marco/be02marbox/domain/user/User.java
  src/main/java/prgrms/marco/be02marbox/domain/user/controller/UserController.java
  src/main/java/prgrms/marco/be02marbox/domain/user/dto/ResponseLoginUser.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/CustomAuthenticationEntryPoint.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthentication.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationProvider.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationToken.java
  src/main/java/prgrms/marco/be02marbox/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/prgrms/marco/be02marbox/config/JwtConfigureTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/UserIntegrationTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/controller/UserControllerTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/CustomAuthenticationEntryPointTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationFilterTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationProviderTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/SecurityTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/service/UserServiceTest.java
  src/test/resources/jwt-config.properties
Labels: Team-Marco, user

#121 [#113] 사용자는 영화의 시간 스케줄을 확인한다
  src/docs/asciidoc/schedule.adoc
  src/main/java/prgrms/marco/be02marbox/domain/exception/custom/Message.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleController.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/dto/ResponseFindTime.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/utils/ScheduleConverter.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleControllerTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceTest.java
Labels: schedule

#128 [#126] 스케줄 별 예약 가능한 좌석 조회 API 구현
  src/docs/asciidoc/reserved_seat.adoc
  src/main/java/prgrms/marco/be02marbox/domain/exception/custom/Message.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/controller/ReservedSeatController.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/service/ReservationService.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/service/ReservedSeatService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/SeatService.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/controller/ReservedSeatControllerTest.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/RepositoryTestUtil.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/service/ReservationServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/service/ReservedSeatServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryTest.java
Labels: Team-Marco, schedule, seat, reserved_seat

#131 [#130] TheaterRoom 리팩터링
  src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/controller/TheaterRoomController.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/dto/ResponseFindTheaterRoom.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/TheaterRoomRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterCommonService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterRoomService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/TheaterService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/utils/TheaterRoomConverter.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/RepositoryTestUtil.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepositoryTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/controller/TheaterRoomControllerTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/service/TheaterCommonServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/service/TheaterRoomServiceTest.java
Labels: Team-Marco, theater, theater_room, refactor

#132 [#129] 로그인 기능 refresh token 추가
  src/docs/asciidoc/user.adoc
  src/main/java/prgrms/marco/be02marbox/config/WebSecurityConfigure.java
  src/main/java/prgrms/marco/be02marbox/domain/exception/custom/Message.java
  src/main/java/prgrms/marco/be02marbox/domain/user/RefreshToken.java
  src/main/java/prgrms/marco/be02marbox/domain/user/User.java
  src/main/java/prgrms/marco/be02marbox/domain/user/controller/UserController.java
  src/main/java/prgrms/marco/be02marbox/domain/user/dto/ResponseJwtToken.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/Jwt.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationProvider.java
  src/main/java/prgrms/marco/be02marbox/domain/user/repository/RefreshTokenRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/user/service/JwtService.java
  src/main/java/prgrms/marco/be02marbox/domain/user/service/RefreshTokenService.java
  src/main/java/prgrms/marco/be02marbox/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/prgrms/marco/be02marbox/domain/user/UserIntegrationTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/controller/UserControllerTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationProviderTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/JwtTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/SecurityTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/service/JwtServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/service/RefreshTokenServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/service/UserServiceTest.java
  src/test/resources/application-integration.yml
Labels: Team-Marco, user

#139 [#122] Schedule 도메인 서비스 코드 주석 추가
  src/main/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleService.java
Labels: schedule

#145 #[144] REAMD ME 내용 추가
  README.md
Labels: Team-Marco, docs

#146 [#133] 메소드 실행 시간 측정
  build.gradle
  src/main/java/prgrms/marco/be02marbox/aop/ExecutionTimer.java
Labels: Task

#159 [#152] README 코드 컨벤션 작성
  README.md
Labels: Team-Marco, docs

#157 [#153] API URI 변경
  src/main/java/prgrms/marco/be02marbox/domain/movie/controller/api/MovieRestController.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/controller/ReservedSeatController.java
  src/test/java/prgrms/marco/be02marbox/domain/movie/controller/api/MovieRestControllerTest.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/controller/ReservedSeatControllerTest.java
Labels: movie, refactor, reserved_seat

#160 [#158] 기획 내용 채우기
  README.md
Labels: Team-Marco, docs

#154 [#140] Logback 설정
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-test.xml
Labels: Team-Marco, Task

#162 [#161] Logback 파일 설정 변경
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-test.xml
Labels: Team-Marco, Task

#165 [#163] README 개발환경 이미지 변경
  README.md
Labels: Team-Marco, docs

#166 [#164] erd, entity diagram 사진 변경
  README.md
Labels: docs

#170 [#169] docs 수정
  .gitignore
  src/docs/asciidoc/ticket.adoc
Labels: Team-Marco, refactor

#172 [#171] README ERD를 Table 설계도로 변경
  README.md
Labels: Team-Marco, docs

#174 [#173] api 문서 제공
  README.md
Labels: Team-Marco, docs

#180 [#179] readme 정리
  README.md
Labels: docs

#182 [#168] RefreshToken 저장소 Redis로 migration
  build.gradle
  docker-compose.yml
  src/main/java/prgrms/marco/be02marbox/config/RedisConfig.java
  src/main/java/prgrms/marco/be02marbox/domain/exception/custom/Message.java
  src/main/java/prgrms/marco/be02marbox/domain/user/RefreshToken.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/Jwt.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthentication.java
  src/main/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/prgrms/marco/be02marbox/domain/user/repository/RefreshTokenRedisRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/user/repository/RefreshTokenRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/user/repository/UserRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/user/service/JwtService.java
  src/main/java/prgrms/marco/be02marbox/domain/user/service/RefreshTokenService.java
  src/main/java/prgrms/marco/be02marbox/domain/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/prgrms/marco/be02marbox/domain/user/UserIntegrationTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/JwtAuthenticationFilterTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/JwtTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/jwt/SecurityTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/service/JwtServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/service/RefreshTokenServiceTest.java
  src/test/resources/application.yml
Labels: Team-Marco, user

#186 [#183] 개발용, 테스트 서버용 docker-compose 분리
  docker-compose.test.yml
Labels: Team-Marco, config

#187 [#184] README 개발환경 이미지 Redis 추가하기
  README.md
Labels: Team-Marco, docs

#193 [#192] /users/refresh 통합 테스트 수정
  src/test/java/prgrms/marco/be02marbox/domain/user/UserIntegrationTest.java
Labels: Team-Marco, hotfix

#189 [#185] 파일 업로드 S3 연동
  .gitignore
  build.gradle
  src/main/java/prgrms/marco/be02marbox/aws/S3Upload.java
  src/main/java/prgrms/marco/be02marbox/config/S3Config.java
  src/main/java/prgrms/marco/be02marbox/domain/movie/service/MovieService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/prgrms/marco/be02marbox/domain/movie/service/MovieServiceTest.java
  src/test/resources/application.yml
Labels: Team-Marco, movie

#198 [#197] 결제 기능을 위한 ERD 수정
  src/main/java/prgrms/marco/be02marbox/domain/reservation/Account.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/Ticket.java
Labels: pay, ticket

#201 [#195] QueryDSL 적용
  build.gradle
  src/main/java/prgrms/marco/be02marbox/config/QueryDslConfig.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepositoryCustom.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/repository/ReservedSeatRepositoryCustomImpl.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/service/TicketService.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryCustom.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryCustomImpl.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepository.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryCustom.java
  src/main/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryCustomImpl.java
  src/test/java/prgrms/marco/be02marbox/domain/movie/repository/MovieRepositoryTest.java
  src/test/java/prgrms/marco/be02marbox/domain/movie/service/MovieServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/repository/RepositoryTestUtil.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/service/AccountServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/reservation/service/TicketServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/repository/ScheduleRepositoryTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/repository/SeatRepositoryTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/service/ScheduleServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/service/TheaterServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/service/RefreshTokenServiceTest.java
  src/test/java/prgrms/marco/be02marbox/domain/user/service/UserServiceTest.java
Labels: Team-Marco, refactor

#204 [#203] Jacoco 도입
  build.gradle
Labels: Team-Marco, config

#206 [#202] 예약 기능 컨트롤러 추가
  src/docs/asciidoc/reservation.adoc
  src/main/java/prgrms/marco/be02marbox/domain/exception/handler/ReservationExceptionHandler.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/controller/ReservationController.java
  src/main/java/prgrms/marco/be02marbox/domain/reservation/service/ReservationService.java
  src/main/resources/static/docs/openapi3.yaml
  src/test/java/prgrms/marco/be02marbox/domain/reservation/controller/ReservationControllerTest.java
Labels: reservation

#207 [#205] s3 default 설정정보 추가
  src/main/resources/application.yml
Labels: Team-Marco, config

#210 [#140] Schedule 도메인 피드백 반영
  src/main/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleController.java
  src/test/java/prgrms/marco/be02marbox/domain/theater/controller/ScheduleControllerTest.java
Labels: refactor
